package App;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import ConnectionBD.ConsultaBD;
import Reportes.MenuReportes;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class MainUI extends javax.swing.JFrame {

    ConsultaBD consulta = new ConsultaBD();
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(64, 64, 64));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        generarReporte = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        Edad = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        Estado = new javax.swing.JComboBox<>();
        EstadoCivil = new javax.swing.JComboBox<>();
        Documento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buscarCedula = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 51, 51));
        Salir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jTable2.setModel(model);
        jTable2.setColumnSelectionAllowed(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 11))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cedula del estudiante:");

        generarReporte.setBackground(new java.awt.Color(153, 153, 255));
        generarReporte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        generarReporte.setText("Reporte");
        generarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReporteActionPerformed(evt);
            }
        });

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });
        Edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EdadKeyTyped(evt);
            }
        });

        Cedula.setToolTipText("");
        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del estudiante");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido del estudiante:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edad del estudiante:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estado:");

        Agregar.setBackground(new java.awt.Color(153, 153, 255));
        Agregar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Modificar.setBackground(new java.awt.Color(153, 153, 255));
        Modificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(153, 153, 255));
        Eliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Nuevo.setBackground(new java.awt.Color(153, 153, 255));
        Nuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Distrito Capital", "Miranda", "Zulia", "Carabobo", "Merida" }));

        EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo" }));
        EstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoCivilActionPerformed(evt);
            }
        });

        Documento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Copia Cedula", "Titulo Bachiller", "Notas Certificadas" }));
        Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado Civil:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Documento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Documento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generarReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generarReporte)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 11))); // NOI18N

        buscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCedulaActionPerformed(evt);
            }
        });
        buscarCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarCedulaKeyTyped(evt);
            }
        });

        Buscar.setBackground(new java.awt.Color(153, 153, 255));
        Buscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buscar por cedula:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salir)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Maneja el evento de acción para agregar un nuevo estudiante.
     *
     * @param evt El evento de acción que se ha producido.
     */
    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // Conectar a la base de datos
        consulta.conectar();

        // Obtener los valores de los campos de entrada
        String nombre = Nombre.getText();
        String apellido = Apellido.getText();
        String edad = Edad.getText();
        String cedula = Cedula.getText();
        int documento = Documento.getSelectedIndex() + 1;
        int estadoCivil = EstadoCivil.getSelectedIndex() + 1;
        int estado = Estado.getSelectedIndex() + 1;

        // Validar los campos de entrada
        if (nombre.isEmpty() || apellido.isEmpty() || edad.isEmpty() || cedula.isEmpty()) {
            // Mostrar mensaje de error si algún campo está vacío
            JOptionPane.showMessageDialog(null, "Rellene los campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (cedula.length() != 8) {
            // Mostrar mensaje de error si la cédula no tiene exactamente 8 dígitos
            JOptionPane.showMessageDialog(null, "La cédula debe tener exactamente 8 dígitos", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (consulta.verificarExistenciaPorCedula(cedula)) {
            // Mostrar mensaje de error si el estudiante ya existe
            JOptionPane.showMessageDialog(null, "El estudiante ya existe", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Confirmar la acción de agregar el estudiante
            int resultado = JOptionPane.showConfirmDialog(null, "¿Deseas agregar al estudiante?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (resultado == JOptionPane.YES_OPTION) {
                // Limpiar los campos de texto
                Limpiar();

                // Intentar agregar el estudiante y mostrar el resultado
                if (consulta.agregarEstudiante(nombre, apellido, edad, cedula, Integer.toString(estadoCivil), Integer.toString(documento), Integer.toString(estado))) {
                    JOptionPane.showMessageDialog(null, "El estudiante se agregó correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "El estudiante no se agregó correctamente", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        // Limpiar los campos de texto después de la operación
        Limpiar();
    }//GEN-LAST:event_AgregarActionPerformed

    private void DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentoActionPerformed

    }//GEN-LAST:event_DocumentoActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadActionPerformed

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed
    /**
     * Maneja el evento de clic en la tabla para seleccionar una fila y mostrar
     * sus datos en los campos de entrada.
     *
     * @param evt El evento de clic del ratón que se ha producido.
     */
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // Obtener la fila que fue clickeada
        int row = jTable2.rowAtPoint(evt.getPoint());

        // Obtener los valores de las celdas en la fila seleccionada
        String nombre = jTable2.getValueAt(row, 0).toString();
        String apellido = jTable2.getValueAt(row, 1).toString();
        String edad = jTable2.getValueAt(row, 2).toString();
        String cedula = jTable2.getValueAt(row, 3).toString();
        String estadoCivil = jTable2.getValueAt(row, 4).toString();
        String documento = jTable2.getValueAt(row, 5).toString();
        String estado = jTable2.getValueAt(row, 6).toString();

        // Rellenar los campos de texto con los valores obtenidos
        Nombre.setText(nombre);
        Apellido.setText(apellido);
        Edad.setText(edad);
        Cedula.setText(cedula);

        // Seleccionar el valor correspondiente en los JComboBox
        seleccionarItem(EstadoCivil, estadoCivil);
        seleccionarItem(Documento, documento);
        seleccionarItem(Estado, estado);
    }//GEN-LAST:event_jTable2MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        consulta.conectar();
        jTable2.setModel(consulta.cargaDataGrid());
    }//GEN-LAST:event_formWindowActivated

    private void EstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoCivilActionPerformed

    }//GEN-LAST:event_EstadoCivilActionPerformed
    /**
     * Muestra un cuadro de diálogo de confirmación para limpiar los datos de
     * los campos de texto.
     *
     * @param evt El evento que desencadenó la acción.
     */
    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // Mostrar un cuadro de diálogo de confirmación
        int resultado = JOptionPane.showConfirmDialog(null, "¿Deseas limpiar los datos?", "Confirmación", JOptionPane.YES_NO_OPTION);

        // Si el usuario selecciona "Sí", limpiar los campos de texto
        if (resultado == JOptionPane.YES_OPTION) {
            Nombre.setText("");
            Apellido.setText("");
            Edad.setText("");
            Cedula.setText("");
        }
    }//GEN-LAST:event_NuevoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0); // Cierra el programa.
    }//GEN-LAST:event_SalirActionPerformed
    /**
     * Maneja la eliminación de un estudiante basado en el texto ingresado en el
     * campo de cédula.
     *
     * @param evt El evento que desencadenó la acción.
     */
    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // Obtener el texto del campo de cédula
        String cedula = Cedula.getText();

        // Conectar a la base de datos
        consulta.conectar();

        // Verificar si la cédula tiene exactamente 8 dígitos
        if (cedula.length() != 8) {
            JOptionPane.showMessageDialog(null, "La cédula debe tener exactamente 8 dígitos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Mostrar un cuadro de diálogo de confirmación para eliminar al estudiante
            int resultado = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar al estudiante?", "Confirmación", JOptionPane.YES_NO_OPTION);

            // Si el usuario selecciona "Sí", proceder con la eliminación
            if (resultado == JOptionPane.YES_OPTION) {
                Limpiar(); // Limpiar los campos de texto
                if (consulta.eliminarUsuario(cedula)) {
                    JOptionPane.showMessageDialog(null, "El estudiante se eliminó correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "El estudiante no existe", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void CedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyPressed

    }//GEN-LAST:event_CedulaKeyPressed
    /**
     * Maneja la entrada de caracteres en un campo de texto para permitir solo
     * números y teclas de retroceso, y limita la longitud del texto a 8
     * caracteres.
     *
     * @param evt El evento de teclado que desencadenó la acción.
     */
    private void CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyTyped
        char c = evt.getKeyChar();

        // Verifica si el carácter es un número (0-9) o una tecla de retroceso (backspace)
        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE)) {
            // Consume el evento para evitar que se procese el carácter si no es un número ni una tecla de retroceso
            evt.consume();
        }

        // Obtener el campo de texto que generó el evento
        JTextField textField = (JTextField) evt.getSource();

        // Limitar la longitud del texto a 8 caracteres
        if (textField.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_CedulaKeyTyped
    /**
     * Maneja la entrada de caracteres en un campo de texto para permitir solo
     * números y teclas de retroceso, y limita la longitud del texto a 2
     * caracteres.
     *
     * @param evt El evento de teclado que desencadenó la acción.
     */
    private void EdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdadKeyTyped
        char c = evt.getKeyChar();

        // Verifica si el carácter es un número (0-9) o una tecla de retroceso (backspace)
        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE)) {
            // Consume el evento para evitar que se procese el carácter si no es un número ni una tecla de retroceso
            evt.consume();
        }

        // Obtener el campo de texto que generó el evento
        JTextField textField = (JTextField) evt.getSource();

        // Limitar la longitud del texto a 2 caracteres
        if (textField.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_EdadKeyTyped
    /**
     * Maneja la acción para modificar los datos de un estudiante. Primero
     * valida la entrada del usuario y verifica la existencia del estudiante en
     * la base de datos. Luego, confirma la intención del usuario de modificar
     * los datos y realiza la actualización en la base de datos si es necesario.
     */
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // Conectar a la base de datos
        consulta.conectar();

        // Obtener el valor de la cédula del campo de texto
        String cedula = Cedula.getText();

        // Validar la cédula ingresada
        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese la cédula del estudiante", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (cedula.length() != 8) {
            JOptionPane.showMessageDialog(null, "La cédula debe tener exactamente 8 dígitos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Verificar si el estudiante existe en la base de datos
            if (consulta.verificarExistenciaPorCedula(cedula)) {
                // Obtener los valores de los otros campos
                String nombre = Nombre.getText();
                String apellido = Apellido.getText();
                String edad = Edad.getText();
                int documento = Documento.getSelectedIndex() + 1;
                int estadoCivil = EstadoCivil.getSelectedIndex() + 1;
                int estado = Estado.getSelectedIndex() + 1;

                // Confirmar la intención del usuario para modificar los datos
                int resultado = JOptionPane.showConfirmDialog(null, "¿Deseas modificar los datos del estudiante?", "Confirmación", JOptionPane.YES_NO_OPTION);
                if (resultado == JOptionPane.YES_OPTION) {
                    // Modificar los datos del estudiante en la base de datos
                    if (consulta.modificarDatosEstudiante(nombre, apellido, edad, cedula, Integer.toString(estadoCivil), Integer.toString(documento), Integer.toString(estado))) {
                        JOptionPane.showMessageDialog(null, "Los datos del estudiante se modificaron correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo modificar los datos del estudiante", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "El estudiante no existe", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        // Limpiar los campos de entrada
        Limpiar();
    }//GEN-LAST:event_ModificarActionPerformed

    private void buscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCedulaActionPerformed
    /**
     * Maneja la acción para buscar un estudiante por su cédula. Verifica la
     * longitud de la cédula, realiza la búsqueda en la base de datos, y
     * actualiza los campos con los datos del estudiante si se encuentra.
     */
    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // Obtener el valor de la cédula del campo de búsqueda
        String cedula = buscarCedula.getText();

        // Validar la longitud de la cédula
        if (cedula.length() != 8) {
            JOptionPane.showMessageDialog(null, "La cédula debe tener exactamente 8 dígitos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Conectar a la base de datos
            consulta.conectar();

            // Buscar los datos del estudiante por cédula
            String[] valoresEstudianteEncontrado = consulta.buscarEstudiantePorCedula(cedula);

            // Verificar si se encontraron datos del estudiante
            if (valoresEstudianteEncontrado != null) {
                // Actualizar los campos con los datos del estudiante
                Nombre.setText(valoresEstudianteEncontrado[1]);
                Apellido.setText(valoresEstudianteEncontrado[2]);
                Edad.setText(valoresEstudianteEncontrado[3]);
                Cedula.setText(valoresEstudianteEncontrado[0]);
                Documento.setSelectedIndex(Integer.parseInt(valoresEstudianteEncontrado[5]) - 1);
                EstadoCivil.setSelectedIndex(Integer.parseInt(valoresEstudianteEncontrado[4]) - 1);
                Estado.setSelectedIndex(Integer.parseInt(valoresEstudianteEncontrado[6]) - 1);
            } else {
                // Mostrar mensaje si no se encontró ningún estudiante
                JOptionPane.showMessageDialog(null, "No se encontró ningún estudiante con la cédula especificada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BuscarActionPerformed
    /**
     * Maneja el evento de tipeo de teclas en el campo de texto para la cédula.
     *
     * @param evt El evento de tipo KeyEvent que se ha producido.
     */
    private void buscarCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarCedulaKeyTyped
        char c = evt.getKeyChar();

        // Verifica si el carácter es un número (0-9) o una tecla de retroceso (backspace)
        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE)) {
            // Consume el evento para que no sea procesado si no es un número ni una tecla de retroceso
            evt.consume();
        }

        // Obtiene el campo de texto que generó el evento
        JTextField textField = (JTextField) evt.getSource();

        // Verifica si el texto del campo alcanza el límite de longitud (8 caracteres)
        if (textField.getText().length() >= 8) {
            evt.consume(); // Consume el evento para evitar que se ingresen más caracteres
        }
    }//GEN-LAST:event_buscarCedulaKeyTyped
    /**
     * Maneja el evento de acción para generar un reporte.
     *
     * @param evt El evento de acción que se ha producido.
     */
    private void generarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReporteActionPerformed
        MenuReportes dialog = new MenuReportes(this, true); // Crear un diálogo modal de reportes
        dialog.setLocationRelativeTo(this); // Centrar el diálogo respecto a la ventana principal
        dialog.setVisible(true); // Mostrar el diálogo
    }//GEN-LAST:event_generarReporteActionPerformed

    /**
     * Selecciona un ítem en un JComboBox basado en el valor deseado.
     *
     * @param <T> El tipo de elementos en el JComboBox.
     * @param comboBox El JComboBox en el que se va a seleccionar el ítem.
     * @param valorDeseado El valor del ítem que se desea seleccionar.
     */
    public static <T> void seleccionarItem(JComboBox<T> comboBox, T valorDeseado) {
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            T item = comboBox.getItemAt(i);

            // Comparar el valor del elemento con el valor deseado
            if (item.equals(valorDeseado)) {
                comboBox.setSelectedIndex(i); // Seleccionar el ítem
                break; // Salir del bucle después de encontrar el ítem
            }
        }
    }

    /**
     * Limpia los campos de texto en el formulario.
     */
    public void Limpiar() {
        Nombre.setText("");  // Limpiar el campo de texto del nombre
        Apellido.setText(""); // Limpiar el campo de texto del apellido
        Edad.setText("");     // Limpiar el campo de texto de la edad
        Cedula.setText("");   // Limpiar el campo de texto de la cédula
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Apellido;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField Cedula;
    private javax.swing.JComboBox<String> Documento;
    private javax.swing.JTextField Edad;
    private javax.swing.JButton Eliminar;
    private javax.swing.JComboBox<String> Estado;
    private javax.swing.JComboBox<String> EstadoCivil;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton Nuevo;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField buscarCedula;
    private javax.swing.JButton generarReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
